apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        ports:
        - containerPort: 2368

        env:
        # Public URL for Ghost
        - name: url
          value: https://zmartin.me
      
        - name: server__trustProxy
          value: "true"
        
        - name: server__host
          value: "0.0.0.0"

        - name: server__hostname
          value: zmartin.me

        - name: server__port
          value: "2368" 
        - name: mail__transport
          value: SMTP

        - name: mail__options__host
          value: mail.smtp2go.com

        - name: mail__options__port
          value: "587"

        - name: mail__options__secure
          value: "starttls"   # true only for port 465

        - name: mail__options__auth__user
          valueFrom:
          secretKeyRef:
          name: ghost-smtp
          key: username

        - name: mail__options__auth__pass
          valueFrom:
          secretKeyRef:
          name: ghost-smtp
          key: password

        - name: mail__from
          value: '"no-reply@zmartin.me'
        
        # Database configuration (must use double underscores)
        - name: database__client
          value: mysql

        - name: database__connection__host
          value: mariadb.default.svc.cluster.local

        - name: database__connection__port
          value: "3306"

        - name: database__connection__database
          value: ghost

        - name: database__connection__user
          value: ghost

        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password

        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content

      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content
