apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-server-ingress
  namespace: ghost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - zmartin.me
      secretName: ghost-tls

  rules:
    - host: ghost.zmartin.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost-server
                port:
                  number: 80
