apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: security-headers@kubernetescrd
spec:
  tls:
    - hosts:
        - vaultwarden.zmartin.me
      secretName: wildcard-zmartin-me
