apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance

resources:
  - ../base

patches:
  - path: patches.yaml
    target:
      kind: Ingress
      name: glance
      namespace: glance
