apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: glance-glance-forward@kubernetescrd

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - glance.zmartin.me
      secretName: wildcard-zmartin-me-tls
  rules:
    - host: glance.zmartin.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 80
