apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml

configMapGenerator:
  - name: glance-config
    files:
      - config/config.yml
      - config/proxmox.yml
      - config/unifi.yml

generatorOptions:
  disableNameSuffixHash: true
