---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-configmap
  namespace: vaultwarden
data:
  SIGNUPS_ALLOWED: "true"
  SMTP_HOST: "mail.smtp2go.com" # <-- Add your own SMTP server fqdn/address
  SMTP_FROM: "no-reply@zmartin.me" # <-- Add your own email sender
  SMTP_PORT: "587"
  SMTP_SECURITY: "starttls"
  DOMAIN: "https://vault.zmartin.me" # <-- Add your own external domain here
  TZ: "America/Detroit" # <-- Add your TZ
  PUSH_ENABLED: "true"
  PUSH_RELAY_BASE_URI: "https://push.bitwarden.com"
