apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`vault.zmartin.me`) && PathPrefix(`/admin`)
      kind: Rule
      priority: 100
      services:
        - name: vaultwarden-service
          port: 80

    - match: Host(`vault.zmartin.me`)
      kind: Rule
      priority: 1
      services:
        - name: vaultwarden-service
          port: 80

  tls:
    secretName: wildcard-zmartin-me-tls
