theme:
  background-color: 0 0 16
  primary-color: 157 47 65
  contrast-multiplier: 1.1

pages:
  - name: Home
#Left Side
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: sunday

          - type: to-do 

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4

          - type: twitch-channels
            channels:
              - theprimeagen
              - darthmicrotransaction
              - piratesoftware
              - christitustech

# Center Section

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw
              - UCR-DXc1voovS8nhAvccRZhg
              - UCSLClJLzdUMRMe0E4SPfc-w
              - UC9x0AN7BWHpCDHSm9NiJFJQ
              - UCOk-gHyjcWZNj3Br4oxwh0A

          - type: group
            widgets:
              - type: reddit
                subreddit: cybersecurity
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true
              - type: reddit
                subreddit: confusedmoney
                show-thumbnails: true
          

          # - type: group
          #   widgets:
          #     - $include: proxmox.yml

          - type: group  
            widgets:
              - $include: unifi.yml

# Right Side
      - size: small
        widgets:
          - type: bookmarks
            groups:
              - links:
                  - title: Unifi
                    url: https://unifi.ui.com
                  - title: Plex
                    url: https://plex.zmartin.me

              - title: Homelab
                color: 200 50 50
                links:
                  - title: Proxmox
                    url: https://proxmox.zmartin.me
                  - title: N8N
                    url: https://n8n.zmartin.me
                  - title: Proxy Manager
                    url: https://proxy.zmartin.me/
                  - title: Thor
                    url: https://thor.zmartin.me/
                  - title: pihole
                    url: https://pi.zmartin.me/admin
                  - title: Portainer
                    url: https://portainer.zmartin.me
                  - title: VS Code
                    url: https://vs.zmartin.me/
                  - title: Home Assistant
                    url: https://ha.zmartin.me

              - title: K3's
                color: 200 50 50
                links: 
                  - title: Rancher
                    url: https://rancher.zmartin.me
                  - title: Gitea 
                    url: https://gitea.zmartin.me
                  - title: Grafana
                    url: https://grafana.zmartin.me
                  - title: PGAdmin
                    url: https://pgadmin.zmartin.me
                  - title: Argos CD 
                    url: https://argoscd.zmartin.me

              - title: Social
                color: 200 50 50
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: MorphMarket
                    url: https://www.morphmarket.com/
                  - title: ProtonMail
                    url: https://protonmail.com

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: HBAR-USD
                name: Hedera              

          - type: dns-stats
            service: pihole-v6
            url: https://192.168.1.243/
            password: ${PIHOLE_PASSWORD}

  # # - name: Docker
  # #   columns:
  # #     - size: small
  # #       widgets:
  # #         # Add widgets here

  #     - size: full
  #       widgets:
  #         # Add widgets here

  #     - size: small
  #       widgets:
  #         # Add widgets here
