apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-zmartin-me
  namespace: monitoring
spec:
  secretName: wildcard-zmartin-me-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  dnsNames:
    - zmartin.me
    - "*.zmartin.me"
