replicaCount: 1

image:
  repository: sevensignal/sonar
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  portHttp: 80
  udpStart: 50000
  udpEnd: 50300

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
