apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://code.forgejo.org/forgejo-helm
    chart: forgejo
    targetRevision: 5.0.0
    helm:
      valueFiles:
        - ../../base/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
