apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs
  namespace: wiki
spec:
  tls:
  - hosts:
    - wiki.zmartin.me
    secretName: wildcard-zmartin-me-tls
  rules:
  - host: wiki.zmartin.me
