apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare
spec:
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port:  metrics
      targetPort:  metrics
