resources:
- namespace.yaml
- ingress.yaml
- authentik-sealedsecret.yaml

helmCharts:
- name: authentik
  repo: https://charts.goauthentik.io
  version: 2025.10.2
  releaseName: authentik
  namespace: authentik
  valuesFile: values.yaml
