resources:
- namespace.yaml
- ingress.yaml
- secret-authentik.yaml

helmCharts:
- name: authentik
  repo: https://charts.goauthentik.io
  version: 2024.10.2
  releaseName: authentik
  namespace: authentik
  valuesFile: values.yaml
